### ISSUE TITLE
why source code have   java and Scala two program language

### ISSUE THREAD

**Issue by idiomaticrefactoring** [cvelazquezr/groum_extractor#1]
Hello,
      I'm very sorry for the stupid question. But I really couldn't understand why exists Java and Scala source code in src folder?
    If the author provide two version of extracting group?

    Wish you happy every day！

**Comment by cvelazquezr** [comment]
Hi,
The authors made some operations in Java and also in Scala, it's also kind of weird for me. Basically in Scala were implemented the operations related with Soot manipulation and in Java were implemented the tasks related with graphs operations.

Have also a very nice day!!!

**Comment by idiomaticrefactoring** [comment]
Thank you very much for your so quick reply, so do you think which source code I choose better ? It seems the java code loss some code such as Main entry. @cvelazquezr

**Comment by cvelazquezr** [comment]
Well you need both, because Scala code calls some Java code. The entry point is through a class in Scala which parses command line arguments.

**Comment by idiomaticrefactoring** [comment]
Thank you
